### ISSUE TITLE
Move enum initializer to be before enumeration cases

### ISSUE THREAD

**Issue by sindresorhus** [SwiftDocOrg/swift-doc#102]
In the HTML output.

I have an enum with a lot of cases and the user has to scroll all the way to the bottom to see the initializer, which I would argue is more important.

**Comment by mattt** [comment]
@sindresorhus Thanks for your feedback on this. This is a detail that I've gone back and forth on. 

The challenge is that enumerations can be used in a few different ways, each prioritizing different information. For example, cases are more important for `RawRepresentable` enumerations,  whereas initializers are more important at other times.

...actually, thinking about this again in relation to a solution proposed for #101: 

> Organize the symbol into a group with others for that protocol that are separate from type-specific declarations.

That would address the `RawRepresentable` case that motivated the current ordering. Given that, I agree — let's switch up the ordering. I can get a PR for that within the hour.
