### ISSUE TITLE
Incorrect indentation in code blocks

### ISSUE THREAD

**Issue by sindresorhus** [SwiftDocOrg/swift-doc#108]
For example, see the code block here: https://sindresorhus.com/playground/KeyboardShortcuts_RecorderCocoa/

<img width="750" alt="Screenshot 2020-05-12 at 16 19 44" src="https://user-images.githubusercontent.com/170270/81659558-66c84080-946c-11ea-85c9-7a48446fafc8.png">

Original source: https://github.com/sindresorhus/KeyboardShortcuts/blob/49b017b2450ac37353934d94d6c64957b62c45b4/Sources/KeyboardShortcuts/RecorderCocoa.swift#L14-L26

**Comment by mattt** [comment]
Related to https://github.com/SwiftDocOrg/SwiftMarkup/issues/1

**Comment by mattt** [comment]
Fixed by #114
