### ISSUE TITLE
Expose deep links in the UI

### ISSUE THREAD

**Issue by sindresorhus** [SwiftDocOrg/swift-doc#110]
For example, in https://sindresorhus.com/playground/KeyboardShortcuts_Name/, it would be nice when I hovered over `init?(raw​Value:​)`, it would show a link icon and clicking it would give me a direct deep link to that method. Like with headers in GitHub readme's.

**Comment by mattt** [comment]
That's a great idea, @sindresorhus.

For posterity, here's a screenshot of how GitHub renders heading anchors:

<img width="206" alt="Screen Shot 2020-05-12 at 12 07 28" src="https://user-images.githubusercontent.com/7659/81734954-2e633b00-9449-11ea-8a3f-2b3163d595ee.png">

**Comment by mattt** [comment]
Fixed by https://github.com/SwiftDocOrg/swift-doc/pull/275
