### ISSUE TITLE
Feature request: publish prebuilt Docker image to Docker Hub to speed up the GitHub Action

### ISSUE THREAD

**Issue by hallee** [SwiftDocOrg/swift-doc#111]
Hi, thanks for making this available as a GitHub Action!

Unfortunately it has to run the `builder` steps of your Dockerfile on each run, which can take 7+ minutes on my GitHub Action instances.

GitHub Actions supports prebuilt Docker images and is much faster using them. If you had a prebuilt Docker image on [Docker Hub](https://hub.docker.com) this would probably run in a few seconds. 

https://help.github.com/en/actions/building-actions/metadata-syntax-for-github-actions#runsimage

> The value can be the Docker base image name, a local Dockerfile in your repository, or a public image in Docker Hub 

I'd open a PR to help with this, but seems like you'll need to set up a Docker Hub user for this project so there's not much I can do.

**Comment by mattt** [comment]
@hallee This is definitely on our radar. Our preference was to use [GitHub Packages](https://github.com/features/packages) as the primary host for pre-built Docker images. Curious to know, do you see any benefit in also publishing to Docker Hub?

**Comment by hallee** [comment]
I think Actions currently only supports remote images from Docker Hub, and not GitHub Package Registry (yet). So the only benefit of Docker Hub is you can do that now instead of waiting for GitHub Actions to support their own Docker registry.

**Comment by mattt** [comment]
Ah, thanks for pointing that out. The [documentation](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontainerimage) mentions a  "public docker registry name" (which I assumed included GitHub Packages), but I wasn't able to find any examples of that in the wild.

I have a Docker Hub organization and repository set up. I'd be very happy to get your help in setting up automatic publishing of nightly and stable (tagged) images. What's your Docker Hub username?

**Comment by LucasCarioca** [comment]
Any progress on this? I removed action from my project because it takes way too long.

**Comment by mattt** [comment]
@hallee Now that beta 4 is out, I'll work to get an official Docker image released and hook that up to the GitHub action (which, for better or for worse, tracks master rather than another branch or a tag).

**Comment by MaxDesiatov** [comment]
I'd be happy to help if there's still anything left to do here?

**Comment by mattt** [comment]
@MaxDesiatov Thanks for putting that Docker image together. I just added you as a collaborator to the swiftdoc org on Docker Hub, so you should be able to publish to https://hub.docker.com/repository/docker/swiftdoc/swift-doc.
