### ISSUE TITLE
Include public extensions of external types

### ISSUE THREAD

**Issue by sindresorhus** [SwiftDocOrg/swift-doc#122]
It seems like swift-doc does not include extensions. My project has a [`NSMenuItem` extension](https://github.com/sindresorhus/KeyboardShortcuts/blob/master/Sources/KeyboardShortcuts/NSMenuItem%2B%2B.swift), which would be nice to also include. Jazzy correctly includes this.

Screenshot:

<img width="974" alt="Screenshot 2020-05-21 at 15 47 52" src="https://user-images.githubusercontent.com/170270/82536051-746f7b80-9b7a-11ea-901e-1435f2b3a021.png">

Live example: https://sindresorhus.com/KeyboardShortcuts/Extensions/NSMenuItem.html

**Comment by mattt** [comment]
That's a great idea. Thanks for pointing this out, @sindresorhus!

**Comment by tanner0101** [comment]
+1 this would be very helpful for Vapor (https://api.vapor.codes). Some of our packages actually consist _only_ of extensions so attempting to generate docs on them fails (https://github.com/vapor/fluent-postgres-driver for example).

**Comment by GalenRhodes** [comment]
I would like to upvote this feature!!!! Then I can stop using Jazzy which is slower than molasses running uphill in January.

**Comment by mattt** [comment]
This has been implemented in the latest release (1.0.0-beta.6)
