### ISSUE TITLE
Group operators separately

### ISSUE THREAD

**Issue by sindresorhus** [SwiftDocOrg/swift-doc#123]
Right-now they're just mixed in the same section as normal methods. I think they're special enough to deserve a separate section.

<img width="943" alt="Screenshot 2020-05-21 at 17 17 24" src="https://user-images.githubusercontent.com/170270/82544020-0b423500-9b87-11ea-8496-469112c9749d.png">

Maybe also the rendering could be improved. A space after the function name and maybe fading out the arguments, as they're not important, or making the operator character bold.

**Comment by mattt** [comment]
Totally agree. That's something I've been meaning to implement for a while now.
