### ISSUE TITLE
swift-doc fails when encountering a directory that is named like a Swift source file

### ISSUE THREAD

**Issue by brandon-haugen** [SwiftDocOrg/swift-doc#13]
Hello! First, swift-doc looks like it could be a really useful tool so thank you!

I attempted to run swift-doc with a project I am working on that relies on [MapboxGeocoder](https://github.com/mapbox/MapboxGeocoder.swift) and I ran into a weird scenario where swift-doc returns an error of

> Error: Error Domain=NSCocoaErrorDomain Code=257 "The file “MapboxGeocoder.swift” couldn’t be opened because you don’t have permission to view it."

The problem seems to be that MapboxGeocoder, when installed via Cocoapods, creates a directory in `/Pods` named `MapboxGeocoder.swift` which swift-doc then tries to read as a Swift source file because it looks like a Swift source file if you just look at the name. Removing MapboxGeocoder from the project I am working on though and then running swift-doc works as expected!

I don't know how common of a problem this is, figured I would at least pass it along as something that I ran into when getting started with trying out swift-doc.

**Comment by mattt** [comment]
Thanks for the kind words, @brandon-haugen and for taking the time to report this. Indeed, the CLI code itself isn’t very rigorous yet; the check for a `.swift` extension is missing (at least) a check for not being a directory. I should have a chance to fix this in the next day or two. Or, if you or anyone else feels so compelled, I’d happily accept a PR with such a patch.

**Comment by mattt** [comment]
@brandon-haugen When you have a chance, could you please confirm that #14 resolves your issue?

**Comment by brandon-haugen** [comment]
@mattt it sure does, thanks!

**Comment by mattt** [comment]
@brandon-haugen Awesome. Thanks again for taking the time to report this and verifying the fix. I just merged that PR and cut a new 0.0.2 release with the fix.
