### ISSUE TITLE
swift doc generate fails when generating html

### ISSUE THREAD

**Issue by JaapWijnen** [SwiftDocOrg/swift-doc#133]
Hi! 
I'm on Ubuntu 18.04.4 LTS installed the Swift 5.2.4 release and built swift doc from source. 
Generating markdown documentation works! But when trying to generate html instead the command fails with `Illegal Instruction (core dumped)`. Any ideas what this could be?
I'm running `swift doc generate ./Sources/ --module-name Vapor --output Documentation --format html`
Some html seems to be generated before crashing (sometimes none at all)

**Comment by JaapWijnen** [comment]
also I'm using master branch for swift doc, which the same as the beta.3 release :) and I'm trying to build the documentation for vapor(master branch) www.github.com/vapor/vapor

**Comment by mattt** [comment]
Fixed by #140. Thanks again for your help with this, @JaapWijnen!
