### ISSUE TITLE
swift doc generate fails when generating markdown

### ISSUE THREAD

**Issue by JaapWijnen** [SwiftDocOrg/swift-doc#134]
Hi!
I'm on Ubuntu 18.04.4 LTS installed the Swift 5.2.4 release and built swift doc from source from the master branch (beta.3).
I wanted to generate documentation for www.github.com/vapor/async-kit (master branch). 
But this fails when using the following command `swift doc generate ./Sources/ --module-name AsyncKit --output Documentation`
It prints the following error: 
`2020-06-12T19:59:49+0000 critical: Unable to construct path for /(_:_:) with baseURL /
Fatal error: file /root/swift-doc/Sources/swift-doc/Supporting Types/Page.swift, line 55
Illegal instruction (core dumped)`
and exits with exit code 132.
Any ideas what could be causing this?

**Comment by a2** [comment]
I'm facing a similar issue:

```
$ swift doc generate my-repo/Sources --module-name MyRepo
2020-06-30T17:00:13-0400 critical: Unable to construct path for /(lhs:rhs:) with baseURL /
Fatal error: file /private/tmp/swift-doc-20200630-24417-jrxtfw/Sources/swift-doc/Supporting Types/Page.swift, line 55
zsh: illegal hardware instruction  swift doc generate my-repo/Sources --module-name MyRepo
```

**Comment by JaapWijnen** [comment]
@kareman Does this fix work? Could you make a PR? :)

**Comment by kareman** [comment]
It does when used on https://github.com/kareman/Patterns , but I haven’t tested it on anything else. I was assuming URLComponents was used to cover some edge case I haven’t thought of, so wasn’t sure how generally useful my fix was, but I can make a PR tomorrow.

**Comment by JaapWijnen** [comment]
Awesome :) Does it need any changes before PR? @mattt will probably review it before merging and note any overseen edge cases?
