### ISSUE TITLE
Inline-assigned property has no displayed type

### ISSUE THREAD

**Issue by a2** [SwiftDocOrg/swift-doc#138]
<img width="867" alt="image" src="https://user-images.githubusercontent.com/241156/86392381-5a40b700-bc69-11ea-9627-ea257ea2ab2f.png">

The following renders as above without the `Bool` type displayed:

```swift
var allowsEncodingAsPlainString = true
```

**Comment by mattt** [comment]
@a2 This is a limitation of using a syntactic parse (see #31). Without more information, it's impossible to know whether `allowsEncodingAsPlainString` is `Bool` or some other type that conforms to `ExpressibleByBooleanLiteral`. For declarations with an implicit type like this, would showing the default value be acceptable in your opinion? (e.g. `var allowsEncodingAsPlainString = true`) What if there was something in the UI (like a ?⃝) with an explanation of what's going on?

**Comment by mattt** [comment]
This is a regression caused by https://github.com/SwiftDocOrg/swift-doc/commit/93b33c1b20b95ea354e0b9f3b9bce6a9717363a4#diff-4082294eb6d0c0415becf026802c8cfcR188. To fix the immediate problem, I have a patch in #150 that only omits initializer clause if its a closure or function call expression. conventional literal expressions (boolean, integer, floating-point, string, array, dictionary, etc.) will now be shown.

**Comment by coybit** [comment]
I ran into a problem that seems to be a special case of this issue. For this piece of code:
``` swift
public struct Vendor {
    var name: String
    var address: String
    
    fileprivate static var main1: Vendor {
        Vendor(name: "test", address: "test")
    }
    
    fileprivate static func main2() -> Vendor {
        Vendor(name: "test", address: "test")
    }
}

fileprivate let main3 = Vendor(name: "test", address: "test")
fileprivate func main4() -> Vendor {
    Vendor(name: "test", address: "test")
}

public class Device {
    public var vendor1: Vendor = Vendor.main1
    public var vendor2: Vendor = Vendor.main2()
    public var vendor3: Vendor = main3
    public var vendor4: Vendor = main4()
}
```
The following document is generated:
![localhost_8000_Device_](https://user-images.githubusercontent.com/2979743/101364104-7f81c300-38a2-11eb-86b2-1cd54d9f73ba.png)


```
swift doc --version
1.0.0-beta.5
```

As you see the initial values of `vendor1` and `vendor3` are exposed.

**Comment by coybit** [comment]
I manged to ommit the initializer clause from the generated document by adding `MemberAccessExprSyntax` (for `vendor1`) and `IdentifierExprSyntax` (for `vendor3`) (`SwiftSyntax+Extensions.swift` file):

``` swift
if let value = binding.initializer?.value,
   value.is(ClosureExprSyntax.self) || value.is(FunctionCallExprSyntax.self) || value.is(MemberAccessExprSyntax.self) || value.is(IdentifierExprSyntax.self)
{
    return binding.withInitializer(nil)
                  .withAccessor(nil)
} else {
    return binding.withAccessor(nil)
}
```

<img width="866" alt="Screenshot 2020-12-07 at 17 29 25" src="https://user-images.githubusercontent.com/2979743/101377161-c5925300-38b1-11eb-82f9-7a802ebbb0ef.png">

I don't know what side-effect this change may have. I'm looking into it.
