### ISSUE TITLE
Publish prebuilt binaries as part of releases

### ISSUE THREAD

**Issue by fkorotkov** [SwiftDocOrg/swift-doc#141]
It will be great to use GitHub Releases and publish prebuilt binaries along side with a release. This will help to speed up installation stem in CI to not spend many minutes in each build on compiling a binary from scratch.

**Comment by mattt** [comment]
Agreed. This is something I'd like to do with the forthcoming release.

**Comment by mattt** [comment]
Resolved by #185. In practice, I've seen this improve CI run times improve by nearly an order of magnitude (30 seconds vs. 6 – 10 minutes).
