### ISSUE TITLE
`on:` parameters rendering with some kind of emoji

### ISSUE THREAD

**Issue by mxcl** [SwiftDocOrg/swift-doc#147]
See here: https://github.com/candor/sublimate/wiki/SublimateModelMiddleware

As an aside: good tool.

**Comment by mattt** [comment]
What is this, a vBulletin forum from the '00s? I don't think I'll ever understand the motivation behind [emoji shortcodes](https://docs.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax#using-emoji)...

Anyway, I found what appears to be a minimally-invasive workaround in appending zero-width spaces after each occurrence of a colon. See #149.

**Before**

<img width="652" alt="Screen Shot 2020-07-31 at 05 56 54" src="https://user-images.githubusercontent.com/7659/89038212-c65c1c80-d2f4-11ea-807b-bade180c893d.png">

**After**

<img width="655" alt="Screen Shot 2020-07-31 at 05 57 56" src="https://user-images.githubusercontent.com/7659/89038228-ccea9400-d2f4-11ea-947e-87439dbba51f.png">

**Comment by mattt** [comment]
Aside: Sublimate looks cool! I've likewise found Vapor's use of `Future`s to be a pain point, and look forward to giving this a try.
