### ISSUE TITLE
lib_InternalSwiftSyntaxParser error on Xcode exec run

### ISSUE THREAD

**Issue by KillianSmith0** [SwiftDocOrg/swift-doc#148]
Hey,

Trying to get the dev environment up and running. 
I've been running through command line via `swift run swift-doc` but would be nice to be able to stepthrough Xcode and debug.

When trying to run the exec through Xcode, I receive this error.

```
dyld: Library not loaded: @rpath/lib_InternalSwiftSyntaxParser.dylib  
Referenced from: ~/pwd/swift-doc/DerivedData/build/Debug/swift-doc   
Reason: image not found
```

Any ideas? Is it because the lack of arguments?

### Environment
Xcode: 11.5
Swift: 5.2.4

Thanks in advance
Killian

**Comment by mattt** [comment]
Hi @KillianSmith0. This issue is discussed in #60, with [a workaround suggested by @kean](https://github.com/SwiftDocOrg/swift-doc/issues/60#issuecomment-611153603) to set the `DYLD_LIBRARY_PATH` environment variable.

**Comment by mattt** [comment]
See https://github.com/SwiftDocOrg/swift-doc/issues/60#issuecomment-832140244
