### ISSUE TITLE
Private in documentation

### ISSUE THREAD

**Issue by fortmarek** [SwiftDocOrg/swift-doc#15]
Hi!
first off, thanks for this tool, it's really awesome so far!
I have just come across one issue - I am not sure if it is a bug or a known limitation - but if I generate the documentation, it also creates a documentation for `private` methods (if they appear in `public` class).
When I looked through the source code, it really does seem that there is `filter` for types, but not their properties themselves.

For example:
[This function](https://github.com/fortmarek/ACKategories/blob/b0d50f2b00eaf72ab9d68fae16e8e3fbd73abd10/ACKategories/Base/FlowCoordinator.swift#L177) is `private` but it appears in the [generated documentation](https://github.com/fortmarek/ACKategories/wiki/Base_FlowCoordinator#checkrootviewcontroller)

**Comment by mattt** [comment]
Thanks for reaching out, @fortmarek. I recently merged a refactoring of how symbol relationships are encoded, which may caused a few regressions. (Fortunately, now that I have a sense of what the behavior _should_ be, I can finally start writing tests to help catch these kinds of problems).

Taking a look at this now.

**Comment by mattt** [comment]
Alright, I was able to reproduce this behavior without a problem. The fix appears to be straightforward, too (3af57a62787e4c928a0c35564caf2a3f29f2013c). This should be resolved in the 0.0.3 release. 

When you have a chance, please re-run your workflow and confirm that everything is working as expected.

**Comment by fortmarek** [comment]
Thanks for the quick response, that has done the trick!

**Comment by mattt** [comment]
Awesome. So glad to hear it, @fortmarek! Thanks again for reporting this.
