### ISSUE TITLE
Help wanted: Integrating with git hooks 

### ISSUE THREAD

**Issue by kandelvijaya** [SwiftDocOrg/swift-doc#161]
Hi there @mattt , thanks for the wonderful work on the doc generator. Afterlong, tonight i'm using this on my company project. 

I have a `pre-push` hook which is something like this:

```sh
rm -rf docs/code/
swift-doc generate XYZ --module-name XYZ --output docs/code --format html --base-url  https://pages.github.bus.company.do/MYTEAM/XYZ/docs/code/

exit 0
```

However on every push; it generates new doc, and updates the generatedAt timestamp. I was looking for a way to exclude generatedAt timestamp via some flag or config. I couldn't see this in the interface provided. 

<img width="1061" alt="Screen Shot 2020-08-04 at 12 45 37 AM" src="https://user-images.githubusercontent.com/4518004/89234304-fd2f7c80-d5eb-11ea-8f42-13fb1188e092.png">

1. Is there any better way to integrate this doc generation on git-hooks level? 
2. If you believe we can ignore the timestamp conditionally then how can i help support you?
3. Or you got any other ideas im unaware of. 

Thanks.

**Comment by mattt** [comment]
Hey @kandelvijaya, to answer your questions:

> 1. Is there any better way to integrate this doc generation on git-hooks level?

I wouldn't recommend git-hooks for this. A CI/CD system like GitHub Actions is a much better fit, I think.

> 2. If you believe we can ignore the timestamp conditionally then how can i help support you?

Why don't you want the timestamp to be updated?

**Comment by kandelvijaya** [comment]
1. My company's project is behind self hosted github enterprise (doesnot have github actions). Its asking you too much but are you aware of some other techniques i can use there? If not, i can investigate using web-hooks. 

2. I was thinking to run swift-doc on `git pre-push` which would update `N number of` doc files to include updated timestamp only. Turning off timestamp was a way to avoid doc update diff for timestamp. This is a workaround. What i want to do is `if there was no public interface change and docuementation change; then skip doc generation`

**Comment by mattt** [comment]
> * My company's project is behind self hosted github enterprise (doesnot have github actions). Its asking you too much but are you aware of some other techniques i can use there? If not, i can investigate using web-hooks.

It all depends on the constraints of your company's setup. Maybe look at other projects that have a CI/CD system and plug into whatever they're using.

> * I did have a idea to have `pre-push` hook that generates doc and commits it and then push inside the hook. I will give it a shot for time-being. On the same note; if i generate markdown file i wonder if there is a timestamp.

CommonMark output generates consistent output for the same input, with the exception of the `_Footer.md` file, which includes a timestamp.
