### ISSUE TITLE
SwiftDoc generate does not remove files when removing symbols

### ISSUE THREAD

**Issue by domcorvasce** [SwiftDocOrg/swift-doc#172]
Suppose you have 3 public symbols, and you remove one of them.
If you regenerate the documentation, the CommonMark file or HTML dirs for the deleted symbol will still be there.

The issue concerns both output formats. It's not really noticeable when generating HTML documentation because `index.html` is updated and does not display the deleted symbols.

**But the associated files / dirs are still there.**

The simplest and cheaper solution would be to remove the output dir and recreate it.
Maybe, a more efficient solution (at least, for very large projects) would involve diffing the parsed symbols, and remove files associated with the deleted symbols. Obviously, we'd need to keep somewhere a list of the latest parsed symbols. I don't know if it's worth the hassle, though.

**Comment by mattt** [comment]
@domcorvasce I think Doxygen has the best strategy of the options listed. At least for me, any potential UX benefits are outweighed by the potential for misuse and abuse.
