### ISSUE TITLE
Error: SwiftSyntax parser library isn't compatible

### ISSUE THREAD

**Issue by rolson** [SwiftDocOrg/swift-doc#176]
To Reproduce:

- install swift-doc via homebrew:
`brew install swiftdocorg/formulae/swift-doc`

- run swift-doc on a directory containing swift source:
`swift doc generate ./Sources --module-name Foo -o ~/foo-swift-doc -f html`

- console spits out this error:
`Error: SwiftSyntax parser library isn't compatible`

I've tried with 6 different versions of Xcode command line tools:
![image](https://user-images.githubusercontent.com/3718875/91876694-3f26ff00-ec3a-11ea-9474-50d2d902de05.png)

**Comment by mattt** [comment]
Sorry to hear that you're having trouble getting this to work, @rolson. Please see [this comment](https://github.com/SwiftDocOrg/swift-doc/issues/165#issuecomment-676606309) on #165 for more information about resolving this.

**Comment by rolson** [comment]
That worked, thank you!
