### ISSUE TITLE
html support

### ISSUE THREAD

**Issue by thecb4** [SwiftDocOrg/swift-doc#18]
Spent the day attempting to add HTML support using [HTMLKit](https://github.com/vapor-community/HTMLKit 

Very rudimentary html page created from the top level symbols

fork is: https://github.com/thecb4/swift-doc.git

If you think it's worth it, I can keep going.

```
<!DOCTYPE html>
<html>
	<head>
		<title>Swift Documentation</title>
		<meta property='og:title' content='Swift Documentation'>
			<meta name='twitter:title' content='Swift Documentation'>
				<meta name='author' content='thebc4'>
					<meta name='twitter:creator' content='_thecb4'>
						<meta name='viewport' content='width=device-width, initial-scale=1.0'>
							<link rel='stylesheet' href='https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css' type='text/css'>
							</head>
							<body>
								<nav class='navbar navbar-light bg-light'>
									<span class='navbar-brand mb-0 h1'>swift-doc</span>
								</nav>
								<div class='p-3'>
									<div class='row'>
										<div class='col-2'>
											<div class='nav flex-column nav-pills' id='v-pills-tab' role='tablist' aria-orientation='vertical'>
												<a class='nav-link active' id='v-pills-Generic-tab' data-toggle='pill' href='#v-pills-Generic' role='tab' aria-controls='v-pills-Generic' aria-selected='false'>Generic</a>
												<a class='nav-link' id='v-pills-Type-tab' data-toggle='pill' href='#v-pills-Type' role='tab' aria-controls='v-pills-Type' aria-selected='false'>Type</a>
												<a class='nav-link' id='v-pills-Contextual-tab' data-toggle='pill' href='#v-pills-Contextual' role='tab' aria-controls='v-pills-Contextual' aria-selected='false'>Contextual</a>
												<a class='nav-link' id='v-pills-SourceFile-tab' data-toggle='pill' href='#v-pills-SourceFile' role='tab' aria-controls='v-pills-SourceFile' aria-selected='false'>SourceFile</a>
												<a class='nav-link' id='v-pills-Unknown-tab' data-toggle='pill' href='#v-pills-Unknown' role='tab' aria-controls='v-pills-Unknown' aria-selected='false'>Unknown</a>
												<a class='nav-link' id='v-pills-Relationship-tab' data-toggle='pill' href='#v-pills-Relationship' role='tab' aria-controls='v-pills-Relationship' aria-selected='false'>Relationship</a>
												<a class='nav-link' id='v-pills-Predicate-tab' data-toggle='pill' href='#v-pills-Predicate' role='tab' aria-controls='v-pills-Predicate' aria-selected='false'>Predicate</a>
												<a class='nav-link' id='v-pills-API-tab' data-toggle='pill' href='#v-pills-API' role='tab' aria-controls='v-pills-API' aria-selected='false'>API</a>
												<a class='nav-link' id='v-pills-CompilationCondition-tab' data-toggle='pill' href='#v-pills-CompilationCondition' role='tab' aria-controls='v-pills-CompilationCondition' aria-selected='false'>CompilationCondition</a>
												<a class='nav-link' id='v-pills-Module-tab' data-toggle='pill' href='#v-pills-Module' role='tab' aria-controls='v-pills-Module' aria-selected='false'>Module</a>
												<a class='nav-link' id='v-pills-Identifier-tab' data-toggle='pill' href='#v-pills-Identifier' role='tab' aria-controls='v-pills-Identifier' aria-selected='false'>Identifier</a>
												<a class='nav-link' id='v-pills-Symbol-tab' data-toggle='pill' href='#v-pills-Symbol' role='tab' aria-controls='v-pills-Symbol' aria-selected='false'>Symbol</a>
												<a class='nav-link' id='v-pills-Component-tab' data-toggle='pill' href='#v-pills-Component' role='tab' aria-controls='v-pills-Component' aria-selected='false'>Component</a>
											</div>
										</div>
										<div class='col-10'>
											<div class='tab-content' id='v-pills-tabContent'>
												<div class='tab-pane fade show active' id='v-pills-Generic' role='tabpanel' aria-labelledby='v-pills-Generic-tab'>
													<h2>Generic</h2>
												</div>
												<div class='tab-pane fade' id='v-pills-Type' role='tabpanel' aria-labelledby='v-pills-Type-tab'>
													<h2>Type</h2>
												</div>
												<div class='tab-pane fade' id='v-pills-Contextual' role='tabpanel' aria-labelledby='v-pills-Contextual-tab'>
													<h2>Contextual</h2>
												</div>
												<div class='tab-pane fade' id='v-pills-SourceFile' role='tabpanel' aria-labelledby='v-pills-SourceFile-tab'>
													<h2>SourceFile</h2>
												</div>
												<div class='tab-pane fade' id='v-pills-Unknown' role='tabpanel' aria-labelledby='v-pills-Unknown-tab'>
													<h2>Unknown</h2>
												</div>
												<div class='tab-pane fade' id='v-pills-Relationship' role='tabpanel' aria-labelledby='v-pills-Relationship-tab'>
													<h2>Relationship</h2>
												</div>
												<div class='tab-pane fade' id='v-pills-Predicate' role='tabpanel' aria-labelledby='v-pills-Predicate-tab'>
													<h2>Predicate</h2>
												</div>
												<div class='tab-pane fade' id='v-pills-API' role='tabpanel' aria-labelledby='v-pills-API-tab'>
													<h2>API</h2>
												</div>
												<div class='tab-pane fade' id='v-pills-CompilationCondition' role='tabpanel' aria-labelledby='v-pills-CompilationCondition-tab'>
													<h2>CompilationCondition</h2>
												</div>
												<div class='tab-pane fade' id='v-pills-Module' role='tabpanel' aria-labelledby='v-pills-Module-tab'>
													<h2>Module</h2>
												</div>
												<div class='tab-pane fade' id='v-pills-Identifier' role='tabpanel' aria-labelledby='v-pills-Identifier-tab'>
													<h2>Identifier</h2>
												</div>
												<div class='tab-pane fade' id='v-pills-Symbol' role='tabpanel' aria-labelledby='v-pills-Symbol-tab'>
													<h2>Symbol</h2>
												</div>
												<div class='tab-pane fade' id='v-pills-Component' role='tabpanel' aria-labelledby='v-pills-Component-tab'>
													<h2>Component</h2>
												</div>
											</div>
										</div>
									</div>
								</div>
								<footer class='footer fixed-bottom py-4 bg-dark text-white-50'>
									<div class='container text-center'>
										<small>Copyright &copy; swift-doc</small>
									</div>
								</footer>
								<script src='https://code.jquery.com/jquery-3.4.1.slim.min.js'></script>
								<script src='https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js'></script>
								<script src='https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js'></script>
							</body>
						</html>
```

**Comment by mattt** [comment]
Hi @thecb4. Thanks so much for taking the time to take a stab at implementing HTML support.

I've been evaluating all of the available options for HTML templating in Swift, but haven't yet found any that I think are suitable. I'm working on a workable solution, and hope to have something to share this week.

In the case of HTMLKit, the deal-breaker for me is how it introduces its own API concepts alongside known HTML primitives. I understand that this is an attempt to simplify common patterns, but I'd much rather that they be introduced in a separate layer, on an opt-in basis (I already know HTML; I don't want to go through another abstraction to get there):

https://github.com/thecb4/swift-doc/blob/master/Sources/swift-doc/Supporting%20Types/HTMLPage.swift#L24-L28

(And this is more of a personal preference, but I'm not a fan of Bootstrap and other frameworks that use classes to style components.)

Thanks again for looking into this @thecb4. I apologize for not communicating more about that process, and not having a better story for contributing to the project right now.

**Comment by thecb4** [comment]
I guess I like HTMLKit because it gives me type safety for HTML which can be a pain to debug. I am not a fan of the error messages you get, but that’s more an issue with Swift’a diagnostic system.

Knowing many of these elements would be repeating, if felt right to use a higher order process than copy/paste, and I didn’t want to introduce another language like nodejs.

🤷🏾‍♂️ 

It was fun learning.


Cheers,
CB

**Comment by mattt** [comment]
> I guess I like HTMLKit because it gives me type safety for HTML which can be a pain to debug

This is something I hear often for these kinds of libraries, so I'd be interested to hear your responses to these questions: 

How often do you find yourself dealing with invalid HTML? How does that compare to the amount of time you spend fighting Xcode to get builder syntax to work?

For something like XML or XHTML, where generated content *must* be 100% valid in order to work, I can absolutely see the benefit of a DSL / generator. But for HTML, I don't think it's as necessary.

My first exposure to higher-ordered abstractions for HTML goes back to [Haml](http://haml.info) in Ruby (and [Markaby](https://en.wikipedia.org/wiki/Markaby) before that). For a while, I chose HAML over [ERB](https://www.rubyguides.com/2018/11/ruby-erb-haml-slim/), but over time, I found the friction of using HAML to greatly outweigh any real benefits. (The same thing happened for Sass over SCSS syntax; it's really nice to be able to copy-paste existing markup without converting to a new syntax).

**Comment by thecb4** [comment]
I struggle more with CSS than anything else, but I do run into issues with ill-formatted HTML (often the closing element). That’s also an issue of having a good editor with autocomplete maybe.  I’m thinking of using HTMLKit to do an update to my static website.

I don’t feel like I’m learning a “new” paradigm as many of the names are the same HTML names in Swift. The only issue I’ve run into was the ForEach. Once I got several cups of coffee I dug into learning SwiftDoc and SwiftMarkup, making HTMLKit work in a similar fashion was just a few hours.

**Comment by mattt** [comment]
@thecb4 Thanks again for sharing your feedback. A few more responses inline below:

> I struggle more with CSS than anything else, but I do run into issues with ill-formatted HTML (often the closing element)

That's surprising to me, given how lenient HTML is with closing tag omission. Can you think of any specific examples where this happened to you recently?

> Once I got several cups of coffee I dug into learning SwiftDoc and SwiftMarkup, making HTMLKit work in a similar fashion was just a few hours.

Let me say again that I really appreciate you taking the time to hack on this. I genuinely don't want this to feel like wasted effort on your part, and hope that you got something out of the experience of building this.

I will say that this issue got me to thinking more critically about what I actually wanted to do with HTML. It forced me to get serious about an idea I'd been playing around with. So at the very least, thanks for giving me the push I needed.

Whenever you have a chance, I'd be very interested to get your feedback about this new library, [HypertextLiteral](https://github.com/NSHipster/HypertextLiteral) and how it compares to HTMLKit. My hope is that you'll be able to get up to speed in minutes, not hours, and not be worse off for lack of functionality.

**Comment by thecb4** [comment]
It may have been more around Divs and css associated with those. Text alignment and image alignment, creating things like Jumbotrons and cards, and footers.

**Comment by thecb4** [comment]
Looking at HyperTextLiteral, my hot take as a choice between this and HTMLKit is that this is verbose compared HTMLKit. I am not a fan of how HTMLKit uses property wrappers, but I do like how clean it is.  I also like [HTML-DSL](https://github.com/robb/HTML-DSL) but it doesn't have any iterators.

**Comment by thecb4** [comment]
So this may be a little cleaner than HTMLKit

```swift
    let articles = [
      "Foo": "Dirty",
      "Bar": "Clean",
      "Baz": "Hairy",
    ]
    
    let root = html(lang: "en-US") {
      "<!-- Generated on: \(Date()) -->"
      body() {
        articles.map { (title, text) in
          article(class: "readme modern") {
            header { h1 { title } }
            p { text }
          }
        }
      }
    }
    
    let path = "/Users/.../toolbox/HTML-DSL/Tests/HTMLTests/fixtures/public/index.html"
    let url = URL(fileURLWithPath: path)
    
    print(String(describing: root))
    
    try root.string.write(to: url, atomically: false, encoding: .utf8)
```

produces

```html

<html lang="en-US">
	<!-- Generated on: 2020-02-22 16:11:04 +0000 -->
	<body>
		<article class="readme modern">
			<header>
				<h1>
					Baz
				</h1>
			</header>
			<p>
				Hairy
			</p>
		</article>
		<article class="readme modern">
			<header>
				<h1>
					Foo
				</h1>
			</header>
			<p>
				Dirty
			</p>
		</article>
		<article class="readme modern">
			<header>
				<h1>
					Bar
				</h1>
			</header>
			<p>
				Clean
			</p>
		</article>
	</body>
</html>
```

**Comment by thecb4** [comment]
Alright! I've switched from HTMLKit to html-dsl and removed any trace of Bootstrap. I have managed to create a single html page that allows you to click through grouped symbols.

I think I also found a bug. When pulling symbol information for computed properties it pulls the entire body of the computed property. Is it supposed to do this?

example: 

```swift
var id: ID = {
        Identifier(pathComponents: context.compactMap {
            ($0 as? Symbol)?.name ?? ($0 as? Extension)?.extendedType
        }, name: name)
    }()
```
https://github.com/thecb4/swift-doc

**Comment by thecb4** [comment]
Spent some time today getting the README incorporated into the HTML file and the ability to pass the name of the module. Some formatting changes to the css and it seems pretty decent.

**Comment by mattt** [comment]
See #21

**Comment by thecb4** [comment]
sliiiiiick UI! Awesome!
