### ISSUE TITLE
Add .md extension to the URLs

### ISSUE THREAD

**Issue by Baaroon** [SwiftDocOrg/swift-doc#182]
Is it possible to add the `.md` extension to the generated link urls in `commonmark` format. 
Unfortunately, when I try to open relative links in Bitbucket repo, they are all broken but if I add the `.md` extension manually to the end of the URLs, they're working fine.
Thanks

**Comment by mattt** [comment]
@Baaroon To answer your question: this behavior isn't currently configurable through `swift-doc`, but you could achieve the same result with a post processing step like this:

```terminal
$ find path/to/Documentation -iname "*.md" -type f -exec sed -E 's/((\\[.+\\])\\((.+)\\))/\\2(\\3.md)/' {} \;
```

That said, I take your point about the current linking behavior, which is currently specific to making it work for GitHub Wiki. There's a strong argument to be made for configuring this behavior (or else, distinguishing this output from a more general purpose CommonMark format).

**Comment by Baaroon** [comment]
Thanks Matt :) 
I'll close the issue for now.

**Comment by byron22seven** [comment]
Hey 👋 
Ran that command and nothing changed... So have to do it manually each time docs are generated :(

 Maybe we can add an extra flag like "--url-type" and options "local", "wiki" etc
Local can generate with "./" and "*.md"
