### ISSUE TITLE
`all.css` file doesn't contain actual CSS

### ISSUE THREAD

**Issue by MaxDesiatov** [SwiftDocOrg/swift-doc#198]
Steps to reproduce (steps for purely macOS builds not available due to #197):

1. Run `docker run --entrypoint /bin/bash -it swiftdoc/swift-doc`
2. In the container shell prompt run `apt-get update && apt-get install git`
3. Run `git clone https://github.com/swiftwasm/JavaScriptKit && cd JavaScriptKit`
4. Run `swift-doc generate --base-url "/JavaScriptKit" --module-name JavaScriptKit --format html Sources`
5. Run `cat .build/documentation/all.css`

Expected result: valid CSS.

Actual result: `  Found` output, [can also be seen deployed to GitHub Pages](https://swiftwasm.github.io/JavaScriptKit/all.css).

**Comment by mattt** [comment]
Sorry for the inconvenience, @MaxDesiatov. Swift Package Manager resources caused a bunch of problems for the beta 5 release. I just reverted #192, and am in the process of cutting a new release. What a mess 😞

**Comment by MaxDesiatov** [comment]
No worries. I wonder if we could add an end-to-end test checking that `all.css` has some valid CSS output?

**Comment by mattt** [comment]
@MaxDesiatov Absolutely. I think a lot more end-to-end testing would help avoid botched releases in the future.

**Comment by MaxDesiatov** [comment]
This is fixed in `master` now, thank you!
