### ISSUE TITLE
JSONEncoder.NonConformingFloatEncodingStrategy.convertToString error

### ISSUE THREAD

**Issue by mackoj** [SwiftDocOrg/swift-doc#2]
Hi @mattt I'm always hitting this issue ?

How could I help fixing it ?

```
Error: invalidValue(-nan, Swift.EncodingError.Context(codingPath: [NestedCodingKeys(stringValue: "totals", intValue: nil), CodingKeys(stringValue: "percent", intValue: nil)], debugDescription: "Unable to encode Double.nan directly in JSON. Use JSONEncoder.NonConformingFloatEncodingStrategy.convertToString to specify how the value should be encoded.", underlyingError: nil))
make: *** [doc] Error 1
```

Thanks,

**Comment by mattt** [comment]
Ah, you know what this is? Zero division by zero. I'm not guarding against `hits` and `misses` being `0`, and hadn't tried running it against a project without any public symbols. Working on a quick fix now.

**Comment by mattt** [comment]
@mackoj Can you check out #5 and confirm that this fixes your issue?

**Comment by mackoj** [comment]
Yes it fixes it thanks

**Comment by mattt** [comment]
Awesome. Thanks, @mackoj!
