### ISSUE TITLE
Question: Generating a list of Standard Library global functions

### ISSUE THREAD

**Issue by svanimpe** [SwiftDocOrg/swift-doc#209]
How can I use SwiftDoc to generate a list of global functions in the Swift Standard Library, similar to what's on https://swiftdoc.org?

I'd like to use this list to update https://github.com/highlightjs/highlight.js/blob/master/src/languages/swift.js

Thanks!

**Comment by mattt** [comment]
@svanimpe Apologies for not responding sooner. One idea for getting a list of symbols would be to open a Swift project in Xcode, command-click on a standard library type, and copy the generated interface into a new file. You could then run something like [`DeclarationCollector`](https://github.com/SwiftDocOrg/SwiftSemantics/blob/main/Sources/SwiftSemantics/DeclarationCollector.swift) on the interface to get a list of symbols.

**Comment by mattt** [comment]
Alternatively, you could try this approach: https://forums.swift.org/t/is-there-a-way-to-dump-the-list-of-all-standard-library-symbols-on-linux/48571
