### ISSUE TITLE
Error: SwiftSyntax parser library isn't compatible

### ISSUE THREAD

**Issue by spnkr** [SwiftDocOrg/swift-doc#211]
I get `Error: SwiftSyntax parser library isn't compatible` when running. Using Xcode 12.2/macOS 10.15.5. Help?

**Comment by mattt** [comment]
@spnkr Could you please share the output of the following commands?

```terminal
$ swift --version
$ swift-doc --version
$ which swift-doc
```

Also, how did you install `swift-doc`? Did you use Homebrew or build from source?

**Comment by AngeloStavrow** [comment]
I'm getting this as well, so I'll go ahead and add my answers to your questions, @mattt. I installed SwiftDoc via Homebrew, and here's the output of the commands:

```
% swift --version
Apple Swift version 5.4 (swiftlang-1205.0.26.9 clang-1205.0.19.55)
Target: x86_64-apple-darwin20.4.0

% swift-doc --version
1.0.0-beta.3

% which swift-doc
/usr/local/bin/swift-doc
```

(I'm not sure how I got onto the beta build, maybe that was because I installed SwiftDoc while I was still running beta versions of Big Sur?)

Let me know if I can provide any further info to troubleshoot!

**Comment by mattt** [comment]
@AngeloStavrow That's quite an old version of `swift-doc`. Please upgrade to the latest by running the following command:

```console
$ brew upgrade swiftdocorg/formulae/swift-doc
```

**Comment by AngeloStavrow** [comment]
Thanks for the quick reply! I'd tried before with just `brew upgrade` to upgrade all formulae; when I try upgrade SwiftDoc specifically with that command, I get:

```bash
% brew upgrade swiftdocorg/formulae/swift-doc
Warning: Calling `cellar` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256` with a `cellar:` argument instead.
Please report this issue to the swiftdocorg/formulae tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/swiftdocorg/homebrew-formulae/Formula/swift-doc.rb:24

Warning: Calling `sha256 "digest" => :tag` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256 tag: "digest"` instead.
Please report this issue to the swiftdocorg/formulae tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/swiftdocorg/homebrew-formulae/Formula/swift-doc.rb:25

==> Upgrading 1 outdated package:
swiftdocorg/formulae/swift-doc 1.0.0-beta.3 -> 1.0.0-beta.6
==> Upgrading swiftdocorg/formulae/swift-doc 1.0.0-beta.3 -> 1.0.0-bet
# [ Removing some "already downloaded" messages here to save space ]
==> Downloading https://github.com/SwiftDocOrg/swift-doc/releases/download/1.0.0
#=#=#                                                                         
curl: (22) The requested URL returned error: 404 
Error: Failed to download resource "swift-doc"
Download failed: https://github.com/SwiftDocOrg/swift-doc/releases/download/1.0.0-beta.5//swift-doc-1.0.0-beta.6.big_sur.bottle.tar.gz
```

I'm not very well informed on how Homebrew does its magic, but it looks like there's a bad download link somewhere?

**Comment by mattt** [comment]
@AngeloStavrow Hmm, that last download link should be `https://github.com/SwiftDocOrg/swift-doc/releases/download/1.0.0-beta.6/swift-doc-1.0.0-beta.6.big_sur.bottle.tar.gz`. The [latest formula](https://github.com/SwiftDocOrg/homebrew-formulae/blob/master/Formula/swift-doc.rb) should have the right link, so let's try untapping to see if that helps:

```console
$ brew uninstall swift-doc
$ brew untap swiftdocorg/formulae
$ brew install swiftdocorg/formulae/swift-doc
```

**Comment by AngeloStavrow** [comment]
Success! Thanks so much for your help, _and_ for the explanation, @mattt. 🙂

**Comment by mattt** [comment]
@AngeloStavrow So glad to hear that got things working for you.

I opened https://github.com/SwiftDocOrg/swift-doc/issues/283 to add these instructions to the README.
