### ISSUE TITLE
swift-doc doesn't seem to detect protocol extension methods

### ISSUE THREAD

**Issue by stephencelis** [SwiftDocOrg/swift-doc#213]
We have a library that centers around a single protocol that is extended with methods (similar to how Combine has a `Publisher` protocol and extends it with `map` and other operations), but these methods don't appear to get picked up by swift-doc

Here's documentation for the protocol: https://pointfreeco.github.io/swift-parsing/Parser/

And here's an example extension method: https://github.com/pointfreeco/swift-parsing/blob/6443f30e5766c2319b58412e7c2687e363b54ff1/Sources/Parsing/Parsers/Map.swift#L1-L15

**Comment by onevcat** [comment]
We have the same situation. For protocols, only the methods/properties requirements are generated. All the public methods in the protocol extension are not detected.

**Comment by Lukas-Stuehrk** [comment]
A fix for this problem was just merged and will be included in the next release. If you want to use it today (or even test the fix), you can compile it from source using the instructions in the README.
