### ISSUE TITLE
error: 'libxml2/libxml/tree.h' file not found #import <libxml2/libxml/tree.h>

### ISSUE THREAD

**Issue by rominawb20** [SwiftDocOrg/swift-doc#214]
Hello! i am working with Ubuntu 20, i have this error when i try to install swift-doc. With brew install, make or  swift build -c release --disable-sandbox --build-path deploy. Please  Help!!

`madmin@DFM03:/opt/swift-5.3.2-RELEASE-ubuntu20.04/usr/bin/swift-doc$ make
<module-includes>:1:10: note: in file included from <module-includes>:1:
#include "libxml2-markup.h"
         ^
/opt/swift-5.3.2-RELEASE-ubuntu20.04/usr/bin/swift-doc/.build/checkouts/Markup/Modules/libxml2-markup.h:3:9: error: 'libxml2/libxml/tree.h' file not found
#import <libxml2/libxml/tree.h>
        ^
/opt/swift-5.3.2-RELEASE-ubuntu20.04/usr/bin/swift-doc/.build/checkouts/Markup/Sources/DOM/Comment.swift:1:8: error: could not build C module 'libxml2'
import libxml2
       ^
[7/28] Compiling cmark utf8.c
make: *** [Makefile:12: /opt/swift-5.3.2-RELEASE-ubuntu20.04/usr/bin/swift-doc/.build/release/swift-doc] Error 1`

**Comment by mattt** [comment]
Hi @rominawb20. It looks like you need to install `libxml2-dev`. Run the following command to install the prerequisites for `swift-doc`:

```terminal
$ apt-get install -y graphviz libxml2-dev
``` 

This wasn't explicitly documented in the README, so I made a few changes (d6749ebecbd4e04aa51c5bf242f2f80b16b2dbb1, 14c0eb0ef003ba6a145dbf8804ca3141d8ab451e, cdac2126028550ce9271dcbfeb0851976bfcde18) — including instructions for running from a Docker container — to help prevent other folks from hitting the same problem in the future.
