### ISSUE TITLE
Remove "BETA" label in the header

### ISSUE THREAD

**Issue by fananek** [SwiftDocOrg/swift-doc#216]
I'm wondering whether "BETA" label can be removed/hidden from header. People who visit documentation site often tend to think that documentation itself is Beta version. And honestly I had the same feeling when I first saw some site generated by SwiftDoc. Especially when there is no reference to SwiftDoc in the header.
<img width="455" alt="Snímek obrazovky 2021-01-21 v 14 14 54" src="https://user-images.githubusercontent.com/54376466/105356471-bbbf7780-5bf3-11eb-8a2b-9d34e5abca4f.png">

The information is already in the page footer.
<img width="425" alt="Snímek obrazovky 2021-01-21 v 14 21 01" src="https://user-images.githubusercontent.com/54376466/105356617-ead5e900-5bf3-11eb-81cc-d703f494f574.png">

**Comment by mattt** [comment]
Thanks for your feedback, @fananek. Until this is removed in a future release, you can either remove `<sup>Beta</sup>` with `sed` or another tool, or add a rule in the CSS to hide it.

```terminal
$ sed -i 's#<sup>Beta</sup>##' *.html
```

```css
header sup { display: none !important; }
```

**Comment by fananek** [comment]
Thanks Matt for prompt response. I can manage it for sure. It’s not a big deal. This was more like a feature request. I can even submit PR if you wish and of course agree with this adjustment.
