### ISSUE TITLE
Github action not generating the wiki doc saying no .swift file found

### ISSUE THREAD

**Issue by jevonmao** [SwiftDocOrg/swift-doc#218]
Link to my CI workflow:
https://github.com/jevonmao/PermissionsSwiftUI/blob/main/.github/workflows/swift.yml

**Comment by mattt** [comment]
@jevonmao Looking at your action and the PermissionsSwiftUI sources provided as inputs, I was unable to find any top-level `public` declarations. If `swift-doc` can't find any, it doesn't have anything to generate documentation for. As noted in #122, APIs added to existing public types aren't currently supported by `swift-doc`. A feature request to support `internal` access level is tracked by #72.
