### ISSUE TITLE
Unable to use in Xcode 11.4 on Catalina

### ISSUE THREAD

**Issue by dagronf** [SwiftDocOrg/swift-doc#22]
I just installed swift-doc (for the first time) using 
```
brew install swiftdocorg/formulae/swift-doc
```
I'm getting the following error when trying to generate any documentation :-
```
usern:$ swift doc Sources/ --output Documentation
Error: SwiftSyntax parser library isn't compatible
usern:$ 
```

I've running Catalina 10.15.4 and Xcode 11.4

Thanks!

**Comment by mattt** [comment]
Hey @dagronf. Thanks for reporting this, and apologies for the inconvenience. I've bumped SwiftDoc to 0.1.0 with a requirement on Xcode 11.4 and Swift 5.2. You should be able to re-install and run `swift-doc` with the following commands:

```terminal
$ brew reinstall swiftdocorg/formulae/swift-doc
$ swift doc generate path/to/Sources
```

**Comment by dagronf** [comment]
Hey mate -- absolutely no problem!  I was just updating a library of my own and thought that it might be good to use a doc generator to generate some nice docs :-)

Thank you so much for the quick update! Amazing.

**Comment by mattt** [comment]
@dagronf I just pushed out 1.0.0-beta.1, which folks have reported successfully running on macOS Catalina with Xcode 11.4. Please let me know if you're still having this problem, and I'd be happy to reopen and take another look. Thanks!

**Comment by dagronf** [comment]
Brilliant mate.  Thanks for the quick turnaround!
