### ISSUE TITLE
It seems that --minimum-access-level is not available for generating documentation

### ISSUE THREAD

**Issue by ascentman** [SwiftDocOrg/swift-doc#220]
Just printed out help for `swift doc generate` and there is no `--minimum-access-level` available there as it is described in the Readme:

![Screenshot 2021-02-24 at 11 02 41](https://user-images.githubusercontent.com/16058309/108976841-9d381a80-7690-11eb-8229-9699f9c5044c.png)

Using of it shows me an error: `Error: Unknown option '--minimum-access-level'`

swift doc --version
1.0.0-beta.5

**Comment by MaxDesiatov** [comment]
Did you install `swift-doc` via Homebrew or Docker? If so, this feature was not available in the 1.0.0-beta.5 release, this feature is still not released, as [shown in `Changelog.md`](https://github.com/SwiftDocOrg/swift-doc/blob/master/Changelog.md#unreleased).

**Comment by ascentman** [comment]
@MaxDesiatov  I have installed it using `homebrew`. Thanks for clarification

**Comment by mattt** [comment]
@ascentman This just landed on master yesterday. If you want to use it today, you can compile it from source using the instructions in the README. Otherwise, you can wait for the next official release.

**Comment by Lukas-Stuehrk** [comment]
@ascentman [Version 1.0.0-beta.6](https://github.com/SwiftDocOrg/swift-doc/releases/tag/1.0.0-beta.6) which includes this feature is now available.
