### ISSUE TITLE
--minimum-access-level option in GitHub Actions

### ISSUE THREAD

**Issue by persello** [SwiftDocOrg/swift-doc#224]
Hello, I'd really like to have the possibility to set a minimum access level in the GitHub Actions yaml file.
I might be wrong, but I didn't find a way to accomplish something similar with the current available parameters.

Is it possible to have such an option?
Thank you,
Riccardo

**Comment by gulivero1773** [comment]
Hello, how --minimum-access-level must work? 
![Снимок экрана 2021-03-16 в 09 23 03](https://user-images.githubusercontent.com/61082418/111270961-37103900-8639-11eb-99f7-9b05cfc337b8.png)

**Comment by Lukas-Stuehrk** [comment]
Hi Riccardo, this is a feature which has been developed already, but there hasn't been a new release yet. That's why it's not available in the GitHub action yet. This will be available in the future when we will release version 1.0.0-beta.6.
