### ISSUE TITLE
Markdown links are created without extension

### ISSUE THREAD

**Issue by KizzyCode** [SwiftDocOrg/swift-doc#225]
Currently markdown links are created without any extension, which breaks navigation in a lot of environments (e.g. plain GitHub/GitLab repos without wiki).

E.g. if I have this tree
```
.
├── AnyArgument.md
├── Home.md
└── ...
```
the `Home.md` file looks like this:
```markdown
# Types

  - [InvalidArgument](./InvalidArgument):
    An invalid argument error
```

I used this command to create the documentation:
```sh
swift doc generate --module-name VirtualFileProvider --output ./Documentation --base-url ./ ./Sources
```

**Comment by mattt** [comment]
Hi @KizzyCode. This was previously discussed in #182.

**Comment by KizzyCode** [comment]
Ah, sorry; I missed this one. Thank you!
