### ISSUE TITLE
How to hide properties and functions when generates documentation?

### ISSUE THREAD

**Issue by zinwalin** [SwiftDocOrg/swift-doc#244]
For some reason, plan to only show some functions and structures in final document. 

Any way to implement this requirement? like using annotation?

**Comment by Lukas-Stuehrk** [comment]
Currently, there's no possibility to exclude symbols from the generated documented, besides changing its access level.

There's already a discussion in #101 to implement the functionality to exclude some declarations from the generated documentation, with some additional discussion added in #142. 

We're very interested in getting your feedback in the discussion of #101 as we are still trying to understand how and why such a feature would be used.

**Comment by zinwalin** [comment]
> Currently, there's no possibility to exclude symbols from the generated documented, besides changing its access level.
> 
> There's already a discussion in #101 to implement the functionality to exclude some declarations from the generated documentation, with some additional discussion added in #142.
> 
> We're very interested in getting your feedback in the discussion of #101 as we are still trying to understand how and why such a feature would be used.

thanks for your reply. The reason why we need this feature is because we don't want to expose internal details for users or companies who will use this document, what they need to know is just what APIs we provide.

will continue on #101 for further discussions.
