### ISSUE TITLE
Implement an asset pipeline for CSS, JavaScript, and images

### ISSUE THREAD

**Issue by mattt** [SwiftDocOrg/swift-doc#44]
[Package Resources](https://github.com/apple/swift-evolution/blob/master/proposals/0271-package-manager-resources.md) offer a way to load CSS and JavaScript from the module bundle (as opposed to our current approach of [hard-coding CSS in a string literal](https://github.com/SwiftDocOrg/swift-doc/blob/70f8e59d503f01494570ef83ced1fbeca98968d0/Sources/swift-doc/Supporting%20Types/CSS.swift#L1)).

Although it looks like the ["Package Manager Extensible Build Tools" proposal](https://github.com/aciidb0mb3r/swift-evolution/blob/extensible-tool/proposals/NNNN-package-manager-extensible-tools.md) is no longer being considered, I think we should be able to leverage [webpack](https://webpack.js.org) (or any of its myriad colleagues) to generate resources on an as-needed basis.

**Comment by mattt** [comment]
The same pipeline can be used to take our [icons](https://github.com/SwiftDocOrg/Swift-Semantic-Icons) [inline them into our CSS](https://github.com/SwiftDocOrg/swift-doc/blob/70f8e59d503f01494570ef83ced1fbeca98968d0/Sources/swift-doc/Supporting%20Types/CSS.swift#L182-L192)

**Comment by kaishin** [comment]
@mattt This is the issue we discussed earlier, right?

**Comment by mattt** [comment]
@kaishin Indeed it is. Any thoughts / opinions?

**Comment by mattt** [comment]
> So from what I gathered so far, here's what we want to achieve:
> 
> 1. Track the CSS (or other pre/post processor) sources in the repository.
> 2. Generate the CSS resources before or during built time (lint, minify, etc).
> 3. Since we can't load these at runtime (SPM limitation), we have to inject them during build time.
> 
> For 1, can we consider using Sass or PostCSS for taking care of things like auto-prefixing, polyfills, etc?

Absolutely. I have a slight preference for PostCSS if it's convenient, but Sass is fine too. 

> For 2, I guess webpack is a good place to start. Not my favorite in terms of overhead, but we can try to keep the config manageable.

Actually, taking another look at the available options, I think [Parcel](https://parceljs.org) looks a bit more palatable, at least for an MVP. 

> For 3, I guess auto-generating the Swift file is one option. Any others that we can consider?

Alternatively, we can just copy the files into the built documentation directory, and have our HTML point to where they'll be. Inlining CSS was something I did primarily to get beta 1 out the door.

**Comment by kaishin** [comment]
> Absolutely. I have a slight preference for PostCSS if it's convenient, but Sass is fine too.

Cool, I can set that up. It's my preference too.

> Actually, taking another look at the available options, I think Parcel looks a bit more palatable, at least for an MVP.

Let's go with Parcel for now. I looked at it a while back and it seemed nicer.

> Alternatively, we can just copy the files into the built documentation directory, and have our HTML point to where they'll be. Inlining CSS was something I did primarily to get beta 1 out the door.

I prefer this option as well. Keeps things tidy at a negligible cost.

> Right now, I'm towards Option C.

C it is. I was going to pitch A initially but you bring up good points about the hard npm dependency.

**Comment by kaishin** [comment]
@mattt Can you assign me to this issue? Not able to do that myself...

**Comment by mattt** [comment]
@kaishin Done. Have fun!

**Comment by kaishin** [comment]
@mattt Let's continue the discussion on the PR draft directly :)
