### ISSUE TITLE
"Permission denied" error, documentation is still generated

### ISSUE THREAD

**Issue by kaishin** [SwiftDocOrg/swift-doc#48]
### Steps to reproduce?

- Project: https://github.com/kaishin/Gifu
- How I installed swift-doc: `git clone` then `make install`
- Exact command: `swift-doc generate ./Sources/ --module-name Gifu --output Documentation --format html`
### Expected behavior

- HTML documentation generated at `./Documentation`
- No error output

### Actual behavior

- HTML documentation generated at `./Documentation`
- The following output
```shell
Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"
Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"
```
### Environment
* OS version: 10.15.4 (19E266)

**Comment by kaishin** [comment]
That’s it. They were missing indeed.

**Comment by kaishin** [comment]
Let me investigate a bit. I shouldn't be sounding so sure 😅 I just wondered why the graphs were missing...

**Comment by kaishin** [comment]
Indeed. This is [the line](https://github.com/SwiftDocOrg/swift-doc/blob/master/Sources/swift-doc/Supporting%20Types/Components/Relationships.swift#L89) throwing the error.

**Comment by AndrewBarba** [comment]
Experiencing the same exact error. Installed via Homebrew
