### ISSUE TITLE
Promise Class Producing Incorrect Name

### ISSUE THREAD

**Issue by AndrewBarba** [SwiftDocOrg/swift-doc#50]
I just tested swift-doc on my package Bluebird: https://github.com/AndrewBarba/Bluebird.swift

The `Promise` class, declared [here](https://github.com/AndrewBarba/Bluebird.swift/blob/master/Sources/Promise.swift), is being generated as `State.​State​Handler.​Promise`. 

`State` and `StateHandler` are two internal enums declared above the Promise class in the same file.

Generated docs: https://andrewbarba.github.io/Bluebird.swift/

Installed on macOS 10.15.4 via Homebrew

**Comment by mattt** [comment]
This should be fixed by #51. Can you please try again building from `master`?

**Comment by mattt** [comment]
I tested this locally with 1.0.0-beta.2, and the generated documentation now has the correct class name.

<img width="1174" alt="Screen Shot 2020-04-08 at 16 30 19" src="https://user-images.githubusercontent.com/7659/78843005-701a4500-79b6-11ea-936b-f384bc43d0a1.png">
