### ISSUE TITLE
Path-relative URLs are not working when deployed to GitHub Pages

### ISSUE THREAD

**Issue by kean** [SwiftDocOrg/swift-doc#56]
Hi, I [deployed](https://kean-org.github.io/docs/nuke-docs-beta/9.0.0) the documentation generated by swift-doc to GitHub pages. There is an issue with path-relative URLs. For example, if you got to [ImageProcessing](https://kean-org.github.io/docs/nuke-docs-beta/9.0.0/ImageProcessing/) page and click of any of the URLs there, e.g. `ImageProcessors.Resize`, it shows 404 page. 

I'm using the latest swift-doc from `master`:

```
commit 0b2291a52f22a30d5e2528f06be79d40cac570cb (HEAD -> master, origin/master, origin/HEAD)
Merge: e5c4b85 0ac5744
Author: Mattt <mattt@me.com>
Date:   Sun Apr 5 08:15:44 2020 -0700

    Merge pull request #53 from SwiftDocOrg/mattt/operator-fix
    
    Fix logic error when classifying operators in generate subcommand
```

**Comment by mattt** [comment]
Hey @kean. This is a known, albeit undocumented limitation, so thanks for reporting it.  Currently, all links are routed using absolute paths, which works for sites hosted at a root domain, but not when they're located in a subdirectory, as in your case.

To solve this correctly, we'll likely need to add a new (optional) parameter to the `generate` subcommand to specify a base URL. If one is specified, it could either be passed to a [`<base>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base) tag in the final HTML, or factored into the `path` helper method.

**Comment by kean** [comment]
Have you considered using using Relative URLs? Something like this should work:

```
<a href="../ImageProcessors_Resize">ImageProcessors.Resize</a>
```

**Comment by mattt** [comment]
As currently implemented, relative links would work on symbol pages, but not for the Home page. 
For me, relative paths rank below the two other approaches I described, primarily because it's dependent on a fixed page routing behavior, which we may decide to change in the future.
