### ISSUE TITLE
dyld: Library not loaded: @rpath/lib_InternalSwiftSyntaxParser.dylib

### ISSUE THREAD

**Issue by kean** [SwiftDocOrg/swift-doc#60]
**Environment**

Xcode 11.4

**Steps**

- Pull the latest `swift-doc` from master
- Open Package.swift
- Run `swift-doc` target or unit tests for `SwiftDoc` library

**Observed result**

dyld: Library not loaded: @rpath/lib_InternalSwiftSyntaxParser.dylib
  Referenced from: /Users/kean/Library/Developer/Xcode/DerivedData/swift-doc-enlnpuwdeszizwbdykidcjodocbk/Build/Products/Debug/swift-doc
  Reason: image not found

**Related**

https://github.com/realm/SwiftLint/issues/3105

**Comment by mattt** [comment]
Also related to https://github.com/SwiftDocOrg/SwiftSemantics/issues/2

**Comment by kean** [comment]
Closing as duplicate.

**Comment by mattt** [comment]
Actually, I think there's some SwiftDoc-specific resolution for this. Until this is resolved in a future version of Xcode, we should at least document this as a Known Issue (similar to what we're doing in SwiftSemantics except, well... less awkwardly-written).

**Comment by kean** [comment]
@mattt, do you know if there is a workaround?

**Comment by mattt** [comment]
@kean Last I checked, you can run `swift package generate-xcodeproj` to generate an Xcode project and then `xed <#Package#>.xcodeproj` to open the generated project directly.

**Comment by kean** [comment]
It results in another issue on my machine.

<img width="280" alt="Screen Shot 2020-04-08 at 12 25 19" src="https://user-images.githubusercontent.com/1567433/78808864-0ab55c80-7994-11ea-9288-15c8d8b9fd5f.png">

**Comment by mattt** [comment]
😞 Woof. Thanks for giving that a try. Sorry that isn't a viable solution in the meantime. I'll work to get that documented as a known issue and keep an eye out for a long-term fix in Xcode.

**Comment by kean** [comment]
Is there any way I can run the executable and/or unit tests with the debugger attached in Xcode?

**Comment by mattt** [comment]
Not that I know of, unfortunately. I've been getting by with Console.app crash logs and `print` statements as needed, but would definitely prefer a real debugging setup.

**Comment by kean** [comment]
Apparently the issue is that [SwiftSyntax](https://github.com/apple/swift-syntax) uses some private library named `lib_InternalSwiftSyntaxParser.dylib`. This library is not yet distributed as part of the OS as of macOS 10.15.4. It is, however, available in Xcode 11.4:

```
/Applications/Xcode.app/Contents/Frameworks/lib_InternalSwiftSyntaxParser.dylib
```

So all we need to do is modify @rpath to make sure that the library is there when swift-doc is executed. Unfortunately, there doesn't seem to be any way to do that using Swift Package Manager.

What you _can_ do is change environment variables, like `DYLD_LIBRARY_PATH`. With this setting, I am now able to run SwiftDoc unit tests.

<img width="895" alt="Screen Shot 2020-04-08 at 15 33 08" src="https://user-images.githubusercontent.com/1567433/78825937-bbc8f080-79ae-11ea-80e8-56ffa41ae486.png">

**Comment by JaapWijnen** [comment]
This doesn't work for me unfortunately. Any updates on how to fix this? Trying to run the swiftdoc tests on a local fork

**Comment by mattt** [comment]
@kean Thanks for sharing your workaround for this issue.

I'm happy to report that I was able to get this working in Xcode 12.5 by using the latest [OSS Toolchain](https://swift.org/download/). I just updated the README to document this with f2e3185.
