### ISSUE TITLE
error: the package dependency graph could not be resolved

### ISSUE THREAD

**Issue by khaledbohout2** [SwiftDocOrg/swift-doc#63]
getting this error after running command  "make install" 

error: the package dependency graph could not be resolved; possibly because of these requirements:    https://github.com/SwiftDocOrg/SwiftSemantics.git @ 0.1.0..<0.2.0 make: *** [swift-doc] Error 1

**Comment by mattt** [comment]
It sounds like you're using an old version of Swift. Can you confirm that you're using Swift 5.2 (Xcode 11.4)?

**Comment by khaledbohout2** [comment]
i am using xcode Version 11.3.1 (11C504) and swift 5 but i can not find any available updates in app store

**Comment by mattt** [comment]
`swift-doc` requires Xcode 11.4 or higher.

You can download the latest version of Xcode here: http://developer.apple.com/xcode/download/

**Comment by khaledbohout2** [comment]
> `swift-doc` requires Xcode 11.4 or higher.
> 
> You can download the latest version of Xcode here: http://developer.apple.com/xcode/download/

ok thanks
