### ISSUE TITLE
Incorrect icon for Typealias declaration in HTML

### ISSUE THREAD

**Issue by mattt** [SwiftDocOrg/swift-doc#64]
As seen in #50, the symbol next to the `Resolver` shows as <kbd>C</kbd> for class instead of <kbd>T</kbd> for typealias.

<img width="1174" alt="Screen Shot 2020-04-08 at 16 30 19" src="https://user-images.githubusercontent.com/7659/78843005-701a4500-79b6-11ea-936b-f384bc43d0a1.png">

**Comment by kean** [comment]
There are other mismatches too, e.g. enumeration cases:

<img width="1116" alt="Screen Shot 2020-04-11 at 16 32 47" src="https://user-images.githubusercontent.com/1567433/79054356-16ae5200-7c12-11ea-9ea3-3981e24fa160.png">
