### ISSUE TITLE
Warning and Error during manual install

### ISSUE THREAD

**Issue by sirshannon** [SwiftDocOrg/swift-doc#68]
Xcode 11.4 on macOS 10.15.4

The [README instructions for manual installation](https://github.com/SwiftDocOrg/swift-doc#manually) direct you to clone the swift-doc repo, cd into the folder, and run `make install`.

When I attempt `make install`, terminal displays a lot of "Cloning" and "Resolving" messages then a warning:
`warning: failed to retrieve search paths with pkg-config; maybe pkg-config is not installed
'libxml2' libxml-2.0.pc: warning: couldn't find pc file`

and then continues to work until it ends with this:

`[45/45] Linking swift-doc
install: chmod 755 /usr/local/bin: Operation not permitted
install: /usr/local/bin/swift-doc: Permission denied
make: *** [install] Error 71`

**Comment by mattt** [comment]
Can you please share the output of running the following command?

```terminal
$ swift --version
```

**Comment by sirshannon** [comment]
`Apple Swift version 5.2 (swiftlang-1103.0.32.1 clang-1103.0.32.29)
Target: x86_64-apple-darwin19.4.0`

**Comment by mattt** [comment]
Alright, thanks for providing that. The warning about libxml2 is unexpected for that configuration, so I'll look into that.

As for the permissions error at the end, it looks like the user that's running `make install` doesn't have write access to `/usr/local/bin`. One way to fix that would be to re-run as `sudo make install`, but that error indicates a possible misconfiguration (maybe [something to look into if you use Homebrew](https://stackoverflow.com/questions/46459152/cant-chown-usr-local-for-homebrew-in-mac-os-x-10-13-high-sierra))

**Comment by sirshannon** [comment]
Thanks. 
I’m not using homebrew (thus the manual install).

**Comment by mattt** [comment]
@sirshannon Following up on this: does running `sudo make install` resolve your issue?

**Comment by sirshannon** [comment]
(I’m late, sorry.)
I don’t like to install with sudo to unless I absolutely have to. For a tool that doesn’t work for me when follow the instructions provided, just to see if running sudo will possibly make it work? I’ll pass. 
If I can help test a working install scenario that doesn’t involve sudo or cocoapods, let me know.
