### ISSUE TITLE
No documentation is created

### ISSUE THREAD

**Issue by dsmurfin** [SwiftDocOrg/swift-doc#90]
No documentation is created when using swift-doc. An empty directory .build/documentation is created, but it has no contents. This happens with every project or package I try it against, regardless of the directory.

I created a new Swift Package from scratch as a test, and made the default struct public, and added some documentation. I have attached the sample project which contains the empty directory.

[MyLibrary.zip](https://github.com/SwiftDocOrg/swift-doc/files/4504047/MyLibrary.zip)

If it's helpful I can also send a much larger package from a real project.

**Comment by mattt** [comment]
Unfortunately, I'm having trouble reproducing this locally.

```terminal
$ curl -L MyLibrary.zip https://github.com/SwiftDocOrg/swift-doc/files/4504047/MyLibrary.zip | jar xv
$ swift run swift-doc generate ./MyLibrary-2/Sources  --module-name "MyLibrary"
$ tree .build/documentation/
.build/documentation/
└── Home.md
$ cat .build/documentation/Home.md
```
~~~markdown
# MyLibrary

My Library

``` swift
public struct MyLibrary
```

This is a test for swift-doc

## Properties

### `text`

This is a variable

``` swift
var text
```
~~~

**Comment by dsmurfin** [comment]
Hi @mattt 

Thanks for taking a look so quickly! I should have tried this earlier, but I just did a brew reinstall swift-doc and now it is working correctly. Not sure quite what has gone on as it was generating the directory. IN case it's useful here's what I was doing otherwise:

Apple Swift version 5.2 (swiftlang-1103.0.32.1 clang-1103.0.32.29)
Target: x86_64-apple-darwin19.4.0

Installed via Homebrew

I've tried various methods, examples:

swift-doc generate /Users/dmurfin/Desktop/MyLibrary --module-name MyLibrary
swift-doc generate ./MyLibrary --module-name MyLibrary
swift-doc generate /Users/dmurfin/Desktop/MyLibrary --module-name MyLibrary --format html
swift-doc generate /Users/dmurfin/Desktop/MyLibrary --module-name MyLibrary2
swift-doc generate /Users/dmurfin/Desktop/MyLibrary --module-name MyLibrary2

Thanks

**Comment by mattt** [comment]
@dsmurfin Glad to hear a reinstall fixed that for you! 

In case you were wondering, here's why I think that wasn't working for you:

Earlier versions of `swift-doc` didn't have a separate subcommand for `generate`. So `swift doc generate foo` would instead be interpreted as "Run swift doc on the directory `generate`". Because `generate` didn't exist, the process would exit immediately. 😓

**Comment by dsmurfin** [comment]
Ah! Right, that sounds highly likely. Thanks again.
