### ISSUE TITLE
CSS doesn't link when generating default HTML format

### ISSUE THREAD

**Issue by captainbarbosa** [SwiftDocOrg/swift-doc#95]
Hi @mattt! Great project. I was poking around and testing the `--format html` option and noticed the `all.css` file isn't linking properly to the generated `index.html` file.

I tried debugging this myself, first by checking `index.html` where it _seems_ to be linked correctly (however I'm not a web developer):

```html
<link rel="stylesheet" type="text/css" href="all.css" media="all" />
```

But when I check out the network console in my browser, it looks like `all.css` is failing:

![image](https://user-images.githubusercontent.com/10850812/80446266-3fe60800-88cb-11ea-947e-5b75ca830a2c.png)

Any idea what could be happening? I'm using 1.0.0-beta.2.

**Comment by captainbarbosa** [comment]
Oh, I think I may have found the cause.

It appears this `base-href` line is causing the file search path for `all.css` be incorrect:

`Index.html`
```html
<head>
    ...
    <base href="/"/>
    <link rel="stylesheet" type="text/css" href="all.css" media="all" />
</head>
```

Changing this from `<base href="/"/>` to `<base href=""/>` fixes the issue, so I think we just need to swap the ordering of [these two lines](https://github.com/SwiftDocOrg/swift-doc/blob/master/Sources/swift-doc/Supporting%20Types/Layout.swift#L14-L15):

```html
<base href=""/>
<link rel="stylesheet" type="text/css" href="all.css" media="all" />
```

I created a pull request for this in https://github.com/SwiftDocOrg/swift-doc/pull/96.

**Comment by captainbarbosa** [comment]
https://github.com/SwiftDocOrg/swift-doc/pull/93 is likely a better solution than this PR, so I'll close this in favor 👍

**Comment by mattt** [comment]
Thanks again for bringing this to our attention, @captainbarbosa. I'll keep this open until after #93 is merged, so that you can confirm the fix for yourself.

**Comment by BilalReffas** [comment]
Hi @mattt thanks for this great project! 
Just wanted to raise that I'm running into this issue as well. I have ´swift-doc 1.0.0-beta.3´ installed on my machine.
